# Generated by Django 5.1 on 2024-08-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=150)),
                ('fabricante', models.CharField(max_length=150)),
                ('modelo', models.CharField(max_length=150)),
                ('numero_de_serie', models.CharField(max_length=150)),
                ('data_compra', models.DateField(blank=True)),
                ('valor_compra', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
    ]
